### ISSUE TITLE
Could not get it to work First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f

### ISSUE THREAD

**Issue by PhilAndrew** [dgraph-io/dgraph4j#9]
```
"C:\Program Files\Java\jdk1.8.0_131\bin\java" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:52608,suspend=y,server=n -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_131\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\rt.jar;C:\home\projects\contractmanagement\playapp\target\scala-2.12\classes;C:\Users\philipandrew\.ivy2\cache\aopalliance\aopalliance\jars\aopalliance-1.0.jar;C:\Users\philipandrew\.ivy2\cache\io.netty\netty-transport\jars\netty-transport-4.1.8.Final.jar;C:\Users\philipandrew\.ivy2\cache\io.netty\netty-resolver\jars\netty-resolver-4.1.8.Final.jar;C:\Users\philipandrew\.ivy2\cache\io.netty\netty-handler-proxy\jars\netty-handler-proxy-4.1.8.Final.jar;C:\Users\philipandrew\.ivy2\cache\io.netty\netty-handler\jars\netty-handler-4.1.8.Final.jar;C:\Users\philipandrew\.ivy2\cache\io.netty\netty-common\jars\netty-common-4.1.8.Final.jar;C:\Users\philipandrew\.ivy2\cache\io.netty\netty-codec-socks\jars\netty-codec-socks-4.1.8.Final.jar;C:\Users\philipandrew\.ivy2\cache\io.netty\netty-codec-http2\jars\netty-codec-http2-4.1.8.Final.jar;C:\Users\philipandrew\.ivy2\cache\io.netty\netty-codec-http\jars\netty-codec-http-4.1.8.Final.jar;C:\Users\philipandrew\.ivy2\cache\io.netty\netty-codec\jars\netty-codec-4.1.8.Final.jar;C:\Users\philipandrew\.ivy2\cache\io.netty\netty-buffer\jars\netty-buffer-4.1.8.Final.jar;C:\Users\philipandrew\.ivy2\cache\io.grpc\grpc-netty\jars\grpc-netty-1.2.0.jar;C:\home\projects\contractmanagement\playapp\lib\dgraph4j-0.8.1.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.scala-logging\scala-logging_2.12\bundles\scala-logging_2.12-3.7.2.jar;C:\Users\philipandrew\.ivy2\cache\com.github.nscala-money\nscala-money-play-json_2.12\jars\nscala-money-play-json_2.12-0.13.0.jar;C:\Users\philipandrew\.ivy2\cache\org.scalatra.scalate\scalate-util_2.12\jars\scalate-util_2.12-1.8.0.jar;C:\Users\philipandrew\.ivy2\cache\org.scalatra.scalate\scalate-core_2.12\jars\scalate-core_2.12-1.8.0.jar;C:\Users\philipandrew\.ivy2\cache\org.scala-lang\scala-compiler\jars\scala-compiler-2.12.2.jar;C:\Users\philipandrew\.ivy2\cache\org.sangria-graphql\sangria_2.12\jars\sangria_2.12-1.3.0.jar;C:\Users\philipandrew\.ivy2\cache\org.sangria-graphql\sangria-streaming-api_2.12\jars\sangria-streaming-api_2.12-1.0.0.jar;C:\Users\philipandrew\.ivy2\cache\org.sangria-graphql\sangria-marshalling-api_2.12\jars\sangria-marshalling-api_2.12-1.0.0.jar;C:\Users\philipandrew\.ivy2\cache\org.sangria-graphql\macro-visit_2.12\jars\macro-visit_2.12-0.1.1.jar;C:\Users\philipandrew\.ivy2\cache\org.parboiled\parboiled_2.12\jars\parboiled_2.12-2.1.4.jar;C:\Users\philipandrew\.ivy2\cache\com.chuusai\shapeless_2.12\bundles\shapeless_2.12-2.3.2.jar;C:\Users\philipandrew\.ivy2\cache\org.webjars\jquery\jars\jquery-3.2.1.jar;C:\Users\philipandrew\.ivy2\cache\org.webjars\font-awesome\jars\font-awesome-4.7.0.jar;C:\Users\philipandrew\.ivy2\cache\org.webjars\bootstrap-datepicker\jars\bootstrap-datepicker-1.4.0.jar;C:\Users\philipandrew\.ivy2\cache\org.webjars\bootstrap\jars\bootstrap-4.0.0-alpha.6-1.jar;C:\Users\philipandrew\.ivy2\cache\org.typelevel\macro-compat_2.12\jars\macro-compat_2.12-1.1.1.jar;C:\Users\philipandrew\.ivy2\cache\org.slf4j\slf4j-api\jars\slf4j-api-1.7.25.jar;C:\Users\philipandrew\.ivy2\cache\org.slf4j\jul-to-slf4j\jars\jul-to-slf4j-1.7.25.jar;C:\Users\philipandrew\.ivy2\cache\org.slf4j\jcl-over-slf4j\jars\jcl-over-slf4j-1.7.25.jar;C:\Users\philipandrew\.ivy2\cache\org.scala-lang.modules\scala-xml_2.12\bundles\scala-xml_2.12-1.0.6.jar;C:\Users\philipandrew\.ivy2\cache\org.scala-lang.modules\scala-parser-combinators_2.12\bundles\scala-parser-combinators_2.12-1.0.6.jar;C:\Users\philipandrew\.ivy2\cache\org.scala-lang.modules\scala-java8-compat_2.12\bundles\scala-java8-compat_2.12-0.8.0.jar;C:\Users\philipandrew\.ivy2\cache\org.scala-lang\scala-reflect\jars\scala-reflect-2.12.2.jar;C:\Users\philipandrew\.ivy2\cache\org.scala-lang\scala-library\jars\scala-library-2.12.2.jar;C:\Users\philipandrew\.ivy2\cache\org.reactivestreams\reactive-streams\jars\reactive-streams-1.0.0.jar;C:\Users\philipandrew\.ivy2\cache\org.codehaus.mojo\animal-sniffer-annotations\jars\animal-sniffer-annotations-1.14.jar;C:\Users\philipandrew\.ivy2\cache\org.apache.commons\commons-lang3\jars\commons-lang3-3.6.jar;C:\Users\philipandrew\.ivy2\cache\joda-time\joda-time\jars\joda-time-2.9.9.jar;C:\Users\philipandrew\.ivy2\cache\javax.transaction\jta\jars\jta-1.1.jar;C:\Users\philipandrew\.ivy2\cache\javax.inject\javax.inject\jars\javax.inject-1.jar;C:\Users\philipandrew\.ivy2\cache\io.jsonwebtoken\jjwt\jars\jjwt-0.7.0.jar;C:\Users\philipandrew\.ivy2\cache\commons-codec\commons-codec\jars\commons-codec-1.10.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe\ssl-config-core_2.12\bundles\ssl-config-core_2.12-0.2.1.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe\config\bundles\config-1.3.1.jar;C:\Users\philipandrew\.ivy2\cache\com.google.j2objc\j2objc-annotations\jars\j2objc-annotations-1.1.jar;C:\Users\philipandrew\.ivy2\cache\com.google.inject.extensions\guice-assistedinject\jars\guice-assistedinject-4.1.0.jar;C:\Users\philipandrew\.ivy2\cache\com.google.inject\guice\jars\guice-4.1.0.jar;C:\Users\philipandrew\.ivy2\cache\com.google.guava\guava\bundles\guava-22.0.jar;C:\Users\philipandrew\.ivy2\cache\com.google.errorprone\error_prone_annotations\jars\error_prone_annotations-2.0.18.jar;C:\Users\philipandrew\.ivy2\cache\com.fasterxml.jackson.datatype\jackson-datatype-jsr310\bundles\jackson-datatype-jsr310-2.8.9.jar;C:\Users\philipandrew\.ivy2\cache\com.fasterxml.jackson.datatype\jackson-datatype-jdk8\bundles\jackson-datatype-jdk8-2.8.9.jar;C:\Users\philipandrew\.ivy2\cache\com.fasterxml.jackson.core\jackson-databind\bundles\jackson-databind-2.8.9.jar;C:\Users\philipandrew\.ivy2\cache\com.fasterxml.jackson.core\jackson-core\bundles\jackson-core-2.8.9.jar;C:\Users\philipandrew\.ivy2\cache\com.fasterxml.jackson.core\jackson-annotations\bundles\jackson-annotations-2.8.9.jar;C:\Users\philipandrew\.ivy2\cache\com.adrianhurt\play-bootstrap_2.12\jars\play-bootstrap_2.12-1.2-P26-B4.jar;C:\Users\philipandrew\.ivy2\cache\com.adrianhurt\play-bootstrap-core_2.12\jars\play-bootstrap-core_2.12-1.2-P26.jar;C:\Users\philipandrew\.ivy2\cache\ch.qos.logback\logback-core\jars\logback-core-1.2.3.jar;C:\Users\philipandrew\.ivy2\cache\ch.qos.logback\logback-classic\jars\logback-classic-1.2.3.jar;C:\Users\philipandrew\.ivy2\cache\org.sangria-graphql\sangria-play-json_2.12\jars\sangria-play-json_2.12-1.0.1.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.akka\akka-http-core_2.12\jars\akka-http-core_2.12-10.0.10.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.akka\akka-http-spray-json_2.12\jars\akka-http-spray-json_2.12-10.0.10.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.akka\akka-http_2.12\jars\akka-http_2.12-10.0.10.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.akka\akka-parsing_2.12\jars\akka-parsing_2.12-10.0.10.jar;C:\Users\philipandrew\.ivy2\cache\io.spray\spray-json_2.12\bundles\spray-json_2.12-1.3.3.jar;C:\Users\philipandrew\.ivy2\cache\com.github.cb372\scalacache-core_2.12\jars\scalacache-core_2.12-0.9.4.jar;C:\Users\philipandrew\.ivy2\cache\com.github.cb372\scalacache-guava_2.12\jars\scalacache-guava_2.12-0.9.4.jar;C:\Users\philipandrew\.ivy2\cache\org.joda\joda-convert\jars\joda-convert-1.8.1.jar;C:\Users\philipandrew\.ivy2\cache\com.github.nscala-money\nscala-money_2.12\jars\nscala-money_2.12-0.13.0.jar;C:\Users\philipandrew\.ivy2\cache\org.joda\joda-money\jars\joda-money-0.12.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.akka\akka-actor_2.12\jars\akka-actor_2.12-2.5.3.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.akka\akka-slf4j_2.12\jars\akka-slf4j_2.12-2.5.3.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.akka\akka-stream_2.12\jars\akka-stream_2.12-2.5.3.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.play\build-link\jars\build-link-2.6.2.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.play\filters-helpers_2.12\jars\filters-helpers_2.12-2.6.2.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.play\play-akka-http-server_2.12\jars\play-akka-http-server_2.12-2.6.2.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.play\play-exceptions\jars\play-exceptions-2.6.2.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.play\play-functional_2.12\jars\play-functional_2.12-2.6.2.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.play\play-guice_2.12\jars\play-guice_2.12-2.6.2.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.play\play-json_2.12\jars\play-json_2.12-2.6.2.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.play\play-logback_2.12\jars\play-logback_2.12-2.6.2.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.play\play-netty-utils\jars\play-netty-utils-2.6.2.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.play\play-server_2.12\jars\play-server_2.12-2.6.2.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.play\play-streams_2.12\jars\play-streams_2.12-2.6.2.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.play\play_2.12\jars\play_2.12-2.6.2.jar;C:\Users\philipandrew\.ivy2\cache\com.typesafe.play\twirl-api_2.12\jars\twirl-api_2.12-1.3.3.jar;C:\Users\philipandrew\.ivy2\cache\org.scaldi\scaldi-jsr330_2.12\jars\scaldi-jsr330_2.12-0.5.9.jar;C:\Users\philipandrew\.ivy2\local\org.scaldi\scaldi-play_2.12\0.5.16\jars\scaldi-play_2.12.jar;C:\Users\philipandrew\.ivy2\cache\org.scaldi\scaldi_2.12\jars\scaldi_2.12-0.5.8.jar;C:\Users\philipandrew\.ivy2\cache\com.github.ben-manes.caffeine\caffeine\jars\caffeine-2.5.2.jar;C:\Users\philipandrew\.ivy2\cache\com.github.cb372\scalacache-caffeine_2.12\jars\scalacache-caffeine_2.12-0.9.4.jar;C:\Users\philipandrew\.ivy2\cache\com.google.code.findbugs\jsr305\jars\jsr305-3.0.0.jar;C:\Users\philipandrew\.ivy2\cache\com.google.code.gson\gson\jars\gson-2.7.jar;C:\Users\philipandrew\.ivy2\cache\com.google.instrumentation\instrumentation-api\jars\instrumentation-api-0.3.0.jar;C:\Users\philipandrew\.ivy2\cache\com.google.protobuf\protobuf-java\bundles\protobuf-java-3.2.0.jar;C:\Users\philipandrew\.ivy2\cache\com.google.protobuf\protobuf-java-util\bundles\protobuf-java-util-3.2.0.jar;C:\Users\philipandrew\.ivy2\cache\io.grpc\grpc-context\jars\grpc-context-1.2.0.jar;C:\Users\philipandrew\.ivy2\cache\io.grpc\grpc-core\jars\grpc-core-1.2.0.jar;C:\Users\philipandrew\.ivy2\cache\io.grpc\grpc-protobuf\jars\grpc-protobuf-1.2.0.jar;C:\Users\philipandrew\.ivy2\cache\io.grpc\grpc-protobuf-lite\jars\grpc-protobuf-lite-1.2.0.jar;C:\Users\philipandrew\.ivy2\cache\io.grpc\grpc-stub\jars\grpc-stub-1.2.0.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.2.3\lib\idea_rt.jar" test.WhatIsIt
Connected to the target VM, address: '127.0.0.1:52608', transport: 'socket'
23:29:15.122 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
23:29:15.127 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
23:29:15.172 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
23:29:15.176 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
23:29:15.177 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
23:29:15.178 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
23:29:15.178 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
23:29:15.179 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
23:29:15.179 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
23:29:15.180 [main] DEBUG io.netty.util.internal.Cleaner0 - java.nio.ByteBuffer.cleaner(): available
23:29:15.181 [main] DEBUG io.netty.util.internal.PlatformDependent - Platform: Windows
23:29:15.181 [main] DEBUG io.netty.util.internal.PlatformDependent - Java version: 8
23:29:15.181 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
23:29:15.181 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
23:29:15.182 [main] DEBUG io.netty.util.internal.PlatformDependent - Javassist: unavailable
23:29:15.182 [main] DEBUG io.netty.util.internal.PlatformDependent - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
23:29:15.183 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: C:\Users\PHILIP~1\AppData\Local\Temp (java.io.tmpdir)
23:29:15.183 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
23:29:15.183 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
23:29:15.183 [main] DEBUG io.netty.util.internal.PlatformDependent - io.netty.maxDirectMemory: 7621050368 bytes
23:29:15.205 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
23:29:15.205 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
23:29:15.208 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
23:29:15.952 [main] DEBUG io.dgraph.client.GrpcDgraphClient - Starting query...
23:29:16.051 [main] DEBUG io.dgraph.client.GrpcDgraphClient - Sending request to Dgraph...
23:29:16.135 [grpc-default-executor-0] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
23:29:16.138 [grpc-default-executor-0] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
23:29:16.138 [grpc-default-executor-0] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.maxRecords: 4
23:29:16.138 [grpc-default-executor-0] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@27b689ca
23:29:16.141 [grpc-default-executor-0] DEBUG io.netty.util.internal.ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0xa90a8e3102d4129f
23:29:16.215 [grpc-default-executor-0] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 9304 (auto-detected)
23:29:16.216 [grpc-default-executor-0] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
23:29:16.216 [grpc-default-executor-0] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
23:29:16.231 [grpc-default-executor-0] DEBUG io.netty.util.NetUtil - Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1)
23:29:16.231 [grpc-default-executor-0] DEBUG io.netty.util.NetUtil - \proc\sys\net\core\somaxconn: 200 (non-existent)
23:29:16.247 [grpc-default-executor-0] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 40:16:7e:ff:fe:a9:74:6e (auto-detected)
23:29:16.269 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 8
23:29:16.270 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 8
23:29:16.270 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
23:29:16.270 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
23:29:16.270 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
23:29:16.270 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
23:29:16.270 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
23:29:16.270 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
23:29:16.270 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
23:29:16.270 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
23:29:16.270 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
23:29:16.279 [grpc-default-executor-0] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
23:29:16.279 [grpc-default-executor-0] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
23:29:16.279 [grpc-default-executor-0] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
23:29:16.288 [grpc-default-executor-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 32768
23:29:16.288 [grpc-default-executor-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
23:29:16.288 [grpc-default-executor-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
23:29:16.288 [grpc-default-executor-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
23:29:16.301 [grpc-default-worker-ELG-1-1] DEBUG io.grpc.netty.NettyClientHandler - 
----------------OUTBOUND--------------------
[id: 0x415f72a3, L:/127.0.0.1:52629 - R:localhost/127.0.0.1:8080] SETTINGS: ack=false, settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
------------------------------------
23:29:16.312 [grpc-default-worker-ELG-1-1] DEBUG io.grpc.netty.NettyClientHandler - 
----------------OUTBOUND--------------------
[id: 0x415f72a3, L:/127.0.0.1:52629 - R:localhost/127.0.0.1:8080] WINDOW_UPDATE: streamId=0, windowSizeIncrement=983041
------------------------------------
23:29:16.326 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - 
----------------OUTBOUND--------------------
[id: 0x7d0df568, L:/0:0:0:0:0:0:0:1:52631 - R:localhost/0:0:0:0:0:0:0:1:8080] SETTINGS: ack=false, settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
------------------------------------
23:29:16.326 [grpc-default-worker-ELG-1-1] DEBUG io.grpc.netty.NettyClientHandler - 
----------------OUTBOUND--------------------
[id: 0x415f72a3, L:/127.0.0.1:52629 - R:localhost/127.0.0.1:8080] GO_AWAY: lastStreamId=0, errorCode=1, length=77, bytes=4669727374207265636569766564206672616d6520776173206e6f742053455454494e47532e204865782064756d7020666f7220666972737420352062797465...
------------------------------------
23:29:16.327 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - 
----------------OUTBOUND--------------------
[id: 0x7d0df568, L:/0:0:0:0:0:0:0:1:52631 - R:localhost/0:0:0:0:0:0:0:1:8080] WINDOW_UPDATE: streamId=0, windowSizeIncrement=983041
------------------------------------
23:29:16.330 [grpc-default-worker-ELG-1-1] DEBUG io.netty.handler.codec.http2.Http2ConnectionHandler - [id: 0x415f72a3, L:/127.0.0.1:52629 - R:localhost/127.0.0.1:8080] Sent GOAWAY: lastStreamId '0', errorCode '1', debugData 'First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f'. Forcing shutdown of the connection.
23:29:16.338 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - 
----------------OUTBOUND--------------------
[id: 0x7d0df568, L:/0:0:0:0:0:0:0:1:52631 - R:localhost/0:0:0:0:0:0:0:1:8080] GO_AWAY: lastStreamId=0, errorCode=1, length=77, bytes=4669727374207265636569766564206672616d6520776173206e6f742053455454494e47532e204865782064756d7020666f7220666972737420352062797465...
------------------------------------
23:29:16.338 [grpc-default-worker-ELG-1-2] DEBUG io.netty.handler.codec.http2.Http2ConnectionHandler - [id: 0x7d0df568, L:/0:0:0:0:0:0:0:1:52631 - R:localhost/0:0:0:0:0:0:0:1:8080] Sent GOAWAY: lastStreamId '0', errorCode '1', debugData 'First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f'. Forcing shutdown of the connection.
Disconnected from the target VM, address: '127.0.0.1:52608', transport: 'socket'
io.grpc.StatusRuntimeException: INTERNAL
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at io.dgraph.proto.DgraphGrpc$DgraphBlockingStub.run(DgraphGrpc.java:197)
	at io.dgraph.client.GrpcDgraphClient.query(GrpcDgraphClient.java:57)
	at io.dgraph.client.GrpcDgraphClient.query(GrpcDgraphClient.java:36)
	at test.WhatIsIt$.main(WhatIsIt.scala:11)
	at test.WhatIsIt.main(WhatIsIt.scala)
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:309)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:217)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:401)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" java.lang.NullPointerException
	at test.WhatIsIt$.main(WhatIsIt.scala:19)
	at test.WhatIsIt.main(WhatIsIt.scala)

Process finished with exit code 1

```

**Comment by PhilAndrew** [comment]
Ok I worked out the problem was that I should connect to port 9080 for GRPC, I need to make sure that port 9080 is exposed from my Docker running of DGraph then connect to that port.

**Comment by PhilAndrew** [comment]
I made a DGraph4S for Scala https://github.com/PhilAndrew/DGraph4S
